spring:
  application:
    name: twoer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080
test:
  data: This is a test
  list: This, is , a, list
